#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5M4BK-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.201' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5RPYV-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.202' 
ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNMGXA-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.203' &
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBSF90EH-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.204' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNPE0H-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.205' 
ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5M57K-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.206' &
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTIVGB4-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.207' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNPHR6-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.208' 
ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5NOIY-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.209' &
ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTK1BVI-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.210' &
ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNPI4O-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.211' &
ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5NVJ6-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.212' &
ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNLOB6-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.213' &
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNPL2G-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.214' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5NVPD-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.215' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNLOGL-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.216' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNS27E-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.217' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5RPT9-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.218' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNLOLX-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.219' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNS77Z-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.220' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBR5RPWU-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.221' 
#ssh cirlab@mac-mini-com1-l2-vcr '/home/cirlab/indriya_upgrade/burn_telosb_test.py telosb /dev/serial/by-id/usb-XBOW_Crossbow_Telos_Rev.B_XBTNMGW8-if00-port0 /home/cirlab/indriya_upgrade/telosb_bin/burn-nodeid.sky.222' 