# server_binaries_dir="/home/xxx/indriya_upgrade/telosb_bin/"
server_binaries_dir="/var/www/files/"
RESULT_DIRECTORY = "/home/xxx/indriya_upgrade/output/"
RESULT_DIRECTORY_WWW =  "/var/www/results/"
gateway_binaries_dir="/home/xxx/elf/"
gateway_source_dir="/home/xxx/indriya_upgrade/"
gateway_user = "xxx"
